{% set name = "python-ligo-lw" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ab2ab858feca6f832f03bb952b2e302279cfb08716bbd0e6b6e0f61a7b3a09a

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # extras for cross-compiling python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - ligo-segments
    - lscsoft-glue >=2.0.0
    - numpy
    - python
    - python-dateutil
    - python-lal >=6.19.0
    - pyyaml
    - six
    - tqdm

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check
    # sanity check command-line scripts
    - ligolw_add --help
    - ligolw_cut --help
    - ligolw_no_ilwdchar --help
    - ligolw_print --help
    - ligolw_segments --help
    - ligolw_sqlite --help

about:
  home: https://git.ligo.org/kipp.cannon/python-ligo-lw
  doc_url: https://docs.ligo.org/kipp.cannon/python-ligo-lw/
  dev_url: https://git.ligo.org/kipp.cannon/python-ligo-lw.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: LIGO Light-Weight XML I/O Library
  description: |
    The LIGO Light-Weight XML format is widely used within gravitational-wave
    data analysis pipelines.  This package provides a Python library to read,
    write, and interact with documents in this format.

extra:
  recipe-maintainers:
    - duncanmmacleod
