{% set name = "python-ligo-lw" %}
{% set version = "1.7.1" %}
{% set sha256 = "0b9476d5edaf17ef9036ec17344645129b752097446d6001725ad41ce7d4f206" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - ligo-common
    - ligo-segments
    - lscsoft-glue
    - python
    - pyyaml
    - python-lal >=6.19.0
    - six
    - tqdm
  run_constrained:
    # pin to lscsoft-glue-2.0.0 to prevent file clobbering
    - lscsoft-glue >=2.0.0

test:
  imports:
    - ligo.lw
    - ligo.lw.array
    - ligo.lw.dbtables
    - ligo.lw.ilwd
    - ligo.lw.ligolw
    - ligo.lw.lsctables
    - ligo.lw.param
    - ligo.lw.table
    - ligo.lw.tokenizer
    - ligo.lw.types
    - ligo.lw.utils
    - ligo.lw.utils.coincs
    - ligo.lw.utils.ligolw_add
    - ligo.lw.utils.ligolw_sqlite
    - ligo.lw.utils.process
    - ligo.lw.utils.search_summary
    - ligo.lw.utils.segments
    - ligo.lw.utils.time_slide
  commands:
    - ligolw_add --help
    - ligolw_cut --help
    - ligolw_no_ilwdchar --help
    - ligolw_print --help
    - ligolw_segments --help
    - ligolw_sqlite --help

about:
  home: https://git.ligo.org/kipp.cannon/python-ligo-lw
  doc_url: https://docs.ligo.org/kipp.cannon/python-ligo-lw/
  dev_url: https://git.ligo.org/kipp.cannon/python-ligo-lw
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: LIGO Light-Weight XML I/O Library
  description: |
    The LIGO Light-Weight XML format is widely used within gravitational-wave
    data analysis pipelines.  This package provides a Python library to read,
    write, and interact with documents in this format.

extra:
  recipe-maintainers:
    - duncanmmacleod
